port: 7880

rtc:
  udp_port: 7882
  tcp_port: 7881
  use_external_ip: false

room:
  max_participants: 5

webhook:
  urls:
    - http://api-web:8080/api/v1/rtc/events
  filter_params:
    include_events:
      - participant_joined
      - participant_left
      - room_finished
