export const RealtimeOperations = {
    MESSAGE_CREATED: 1,
    CHANNEL_CREATED: 2,
    CHANNEL_UPDATED: 3,
    CHANNEL_DELETED: 4,
    VOICE_USER_JOINED: 5,
    VOICE_USER_LEFT: 6,
    VOICE_CHANNEL_CLOSED: 7,
    SERVER_ACTIVE: 200,
    TYPING_START: 201,
    TYPING_STOP: 202,
    MEMBER_STATUS_SNAPSHOT: 300,
    MEMBER_STATUS: 301,
}
