export const RealtimeOperations = {
    MESSAGE_CREATED: 1,
    CHANNEL_CREATED: 2,
    CHANNEL_UPDATED: 3,
    CHANNEL_DELETED: 4,

    VOICE_PARTICIPANT_JOINED: 5,
    VOICE_PARTICIPANT_LEFT: 6,
    VOICE_CHANNEL_CLOSED: 7,

    CLIENT_SERVER_ACTIVE: 200,
    CLIENT_START_TYPING: 201,
    CLIENT_STOP_TYPING: 202,

    GW_MEMBER_STATUS_SNAPSHOT: 300,
    GW_MEMBER_STATUS: 301
}